import type { Question } from "./types";

export const questions: Question[] = [
  {
    id: "differentiate-quadratic",
    instruction: "次の式を微分しなさい",
    display: "f(x) = x² + 3x",
    display_latex: "f(x)=x^2+3x",
    category: "微分",
    difficulty: 4,
    difficulty_label: "高校",
  },
  {
    id: "expand-binomial",
    instruction: "次の式を展開しなさい",
    display: "(x + 2)²",
    display_latex: "(x+2)^2",
    category: "展開",
    difficulty: 3,
    difficulty_label: "中学校",
  },
  {
    id: "solve-linear",
    instruction: "方程式を解きなさい",
    display: "2x + 6 = 0",
    display_latex: "2x+6=0",
    category: "方程式",
    difficulty: 3,
    difficulty_label: "中学校",
  },
  {
    id: "evaluate-power",
    instruction: "計算しなさい",
    display: "2⁵",
    display_latex: "2^5",
    category: "指数",
    difficulty: 1,
    difficulty_label: "小学校低学年",
  },
  {
    id: "evaluate-root",
    instruction: "計算しなさい",
    display: "√49",
    display_latex: "\\sqrt{49}",
    category: "平方根",
    difficulty: 3,
    difficulty_label: "中学校",
  },
  {
    id: "differentiate-sine",
    instruction: "次の式を微分しなさい",
    display: "f(x) = sin x",
    display_latex: "f(x)=\\sin x",
    category: "微分",
    difficulty: 4,
    difficulty_label: "高校",
  },
  {
    id: "simplify-fraction",
    instruction: "式を簡単にしなさい",
    display: "6x ÷ 3",
    display_latex: "6x\\div3",
    category: "式の計算",
    difficulty: 2,
    difficulty_label: "小学校高学年",
  },
];

